version: "3"

services:
  node:
    build: ./docker/node
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    working_dir: /CursoWebJavascriptCompleto
    # environment:
    #   - WDS_SOCKET_HOST=127.0.0.1 
    #   - CHOKIDAR_USEPOLLING=true
    #   - WATCHPACK_POLLING=true 
    # ports:
    #   - "3000:3000"

  anaconda:
    build: ./docker/anaconda
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    working_dir: /DataScience_FernandoAmaral/Python

  r:
    build: ./docker/r
    entrypoint:
      - sleep
      - infinity
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    working_dir: /DataScience_FernandoAmaral/R
